In [1]:
import numpy as np

c:\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
rand_int = np.random.randint(0, 100, 10)

In [3]:
rand_int

array([10, 17, 38, 61, 46,  0, 20, 90, 48, 23])

In [4]:
sort_idx = np.argsort(rand_int)

In [7]:
print(sort_idx)
print(rand_int)
print(rand_int[sort_idx])

[5 0 1 6 9 2 4 8 3 7]
[10 17 38 61 46  0 20 90 48 23]
[ 0 10 17 20 23 38 46 48 61 90]
